---
kind: pipeline
name: default
type: kubernetes

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ghcr.io/codestation/drone-kaniko
    settings:
      repo: registry.megpoid.dev/codestation/openconnect-gp
      tags: latest
      registry: registry.megpoid.dev
      config:
        from_secret: registry_credentials

trigger:
  branch:
    - master
